# Questions to answer through the analysis
- Remove the column that only contains missing values.
- Question ( Based on Filtering + Value Counts ) - For Speeding , were Men or Women stopped more often ? 
- Does gender affect who gets searched during a stop ?
- ( mapping + data-type casting ) - What is the mean stop_duration ?
- Compare the age distributions for each violation.

# Visualization Ideas
- Explore the stops through the years
- Explore the stops for each time of day
- The most common reasons for stopping (violation)
- Which gender has the most stops (Maybe percentage is better to describe not the total count)
- Which race ///////
- What is the outcome that happens most often
- Drugs related incidents percentage

## Gather

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Police Data.csv')

In [3]:
df

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,1/23/2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2/20/2005,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65530,12/6/2012,17:54,NaN,F,1987.0,25.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
65531,12/6/2012,22:22,NaN,M,1954.0,58.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
65532,12/6/2012,23:20,NaN,M,1985.0,27.0,Black,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False
65533,12/7/2012,0:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False
65534,12/7/2012,0:30,NaN,F,1985.0,27.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

## Assess

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65535 entries, 0 to 65534
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           65535 non-null  object
 1   stop_time           65535 non-null  object
 2   country_name        0 non-null      float64
 3   driver_gender       61474 non-null  object
 4   driver_age_raw      61481 non-null  float64
 5   driver_age          61228 non-null  float64
 6   driver_race         61475 non-null  object
 7   violation_raw       61475 non-null  object
 8   violation           61475 non-null  object
 9   search_conducted    65535 non-null  bool
 10  search_type         2479 non-null   object
 11  stop_outcome        61475 non-null  object
 12  is_arrested         61475 non-null  object
 13  stop_duration       61475 non-null  object
 14  drugs_related_stop  65535 non-null  bool
dtypes: bool(2), float64(3), object(10)
memory usage: 6.6+ MB

In [5]:
df.isnull().sum()

stop_date                 0
stop_time                 0
country_name          65535
driver_gender          4061
driver_age_raw         4054
driver_age             4307
driver_race            4060
violation_raw          4060
violation              4060
search_conducted          0
search_type           63056
stop_outcome           4060
is_arrested            4060
stop_duration          4060
drugs_related_stop        0
dtype: int64

In [6]:
df.stop_duration.value_counts()

0-15 Min     47379
16-30 Min    11448
30+ Min       2647
2                1
Name: stop_duration, dtype: int64

In [7]:
df.search_conducted.value_counts()

False    63056
True      2479
Name: search_conducted, dtype: int64

In [8]:
df.driver_race.value_counts()

White       45747
Black        8267
Hispanic     5611
Asian        1639
Other         211
Name: driver_race, dtype: int64

In [9]:
df.driver_gender.value_counts()

M    45164
F    16310
Name: driver_gender, dtype: int64

# ÙŽQuality Issues
- driver_age_raw and violation_raw can be deleted DONE
- driver_age should be integer   DONE
- search_type and country_name almost all of them are null so drop the columns DONE
- drop the other nulls in the rows    DONE
- get a mean vallue for the stop_duration and put it in an integer type  DONE
- stop_time should be a represented properly DONE


# Tidiness Issues

## Clean

In [10]:
dfc = df.copy()

- driver_age_raw and violation_raw can be deleted
- search_type and country_name almost all of them are null so drop the columns
#### Define
- use drop method
#### Code & Test

In [11]:
dfc.drop(['driver_age_raw','violation_raw','search_type','country_name'], axis = 1, inplace = True)

In [12]:
dfc

,stop_date,stop_time,driver_gender,driver_age,driver_race,violation,search_conducted,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,M,20.0,White,Speeding,False,Citation,False,0-15 Min,False
1,1/18/2005,8:15,M,40.0,White,Speeding,False,Citation,False,0-15 Min,False
2,1/23/2005,23:15,M,33.0,White,Speeding,False,Citation,False,0-15 Min,False
3,2/20/2005,17:15,M,19.0,White,Other,False,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,F,21.0,White,Speeding,False,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...
65530,12/6/2012,17:54,F,25.0,White,Speeding,False,Citation,False,0-15 Min,False
65531,12/6/2012,22:22,M,58.0,White,Speeding,False,Warning,False,0-15 Min,False
65532,12/6/2012,23:20,M,27.0,Black,Equipment,False,Citation,False,0-15 Min,False
65533,12/7/2012,0:23,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,False
65534,12/7/2012,0:30,F,27.0,White,Speeding,False,Citation,False,0-15 Min,False

- drop the other nulls in the rows
#### Define
- use dropna
#### Code & Test

In [13]:
dfc.dropna(inplace = True)
dfc

,stop_date,stop_time,driver_gender,driver_age,driver_race,violation,search_conducted,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,M,20.0,White,Speeding,False,Citation,False,0-15 Min,False
1,1/18/2005,8:15,M,40.0,White,Speeding,False,Citation,False,0-15 Min,False
2,1/23/2005,23:15,M,33.0,White,Speeding,False,Citation,False,0-15 Min,False
3,2/20/2005,17:15,M,19.0,White,Other,False,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,F,21.0,White,Speeding,False,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...
65529,12/6/2012,16:00,M,18.0,White,Speeding,False,Citation,False,0-15 Min,False
65530,12/6/2012,17:54,F,25.0,White,Speeding,False,Citation,False,0-15 Min,False
65531,12/6/2012,22:22,M,58.0,White,Speeding,False,Warning,False,0-15 Min,False
65532,12/6/2012,23:20,M,27.0,Black,Equipment,False,Citation,False,0-15 Min,False
65534,12/7/2012,0:30,F,27.0,White,Speeding,False,Citation,False,0-15 Min,False

In [14]:
dfc.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 61222 entries, 0 to 65534
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           61222 non-null  object
 1   stop_time           61222 non-null  object
 2   driver_gender       61222 non-null  object
 3   driver_age          61222 non-null  float64
 4   driver_race         61222 non-null  object
 5   violation           61222 non-null  object
 6   search_conducted    61222 non-null  bool
 7   stop_outcome        61222 non-null  object
 8   is_arrested         61222 non-null  object
 9   stop_duration       61222 non-null  object
 10  drugs_related_stop  61222 non-null  bool
dtypes: bool(2), float64(1), object(8)
memory usage: 4.8+ MB

- driver_age should be integer
#### Define
- use astype to convert
#### Code & Test

In [15]:
dfc.driver_age = dfc.driver_age.astype(int)
dfc

,stop_date,stop_time,driver_gender,driver_age,driver_race,violation,search_conducted,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,M,20,White,Speeding,False,Citation,False,0-15 Min,False
1,1/18/2005,8:15,M,40,White,Speeding,False,Citation,False,0-15 Min,False
2,1/23/2005,23:15,M,33,White,Speeding,False,Citation,False,0-15 Min,False
3,2/20/2005,17:15,M,19,White,Other,False,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,F,21,White,Speeding,False,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...
65529,12/6/2012,16:00,M,18,White,Speeding,False,Citation,False,0-15 Min,False
65530,12/6/2012,17:54,F,25,White,Speeding,False,Citation,False,0-15 Min,False
65531,12/6/2012,22:22,M,58,White,Speeding,False,Warning,False,0-15 Min,False
65532,12/6/2012,23:20,M,27,Black,Equipment,False,Citation,False,0-15 Min,False
65534,12/7/2012,0:30,F,27,White,Speeding,False,Citation,False,0-15 Min,False

In [16]:
dfc.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 61222 entries, 0 to 65534
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           61222 non-null  object
 1   stop_time           61222 non-null  object
 2   driver_gender       61222 non-null  object
 3   driver_age          61222 non-null  int32
 4   driver_race         61222 non-null  object
 5   violation           61222 non-null  object
 6   search_conducted    61222 non-null  bool
 7   stop_outcome        61222 non-null  object
 8   is_arrested         61222 non-null  object
 9   stop_duration       61222 non-null  object
 10  drugs_related_stop  61222 non-null  bool
dtypes: bool(2), int32(1), object(8)
memory usage: 4.6+ MB

- stop_time should be a represented properly
#### Define
- use zfill
#### Code & Test

In [17]:
dfc.stop_time

0         1:55
1         8:15
2        23:15
3        17:15
4        10:00
         ...
65529    16:00
65530    17:54
65531    22:22
65532    23:20
65534     0:30
Name: stop_time, Length: 61222, dtype: object

In [18]:
dfc.stop_time = dfc.stop_time.str.zfill(5)
dfc.stop_time

0        01:55
1        08:15
2        23:15
3        17:15
4        10:00
         ...
65529    16:00
65530    17:54
65531    22:22
65532    23:20
65534    00:30
Name: stop_time, Length: 61222, dtype: object

- get a mean vallue for the stop_duration and put it as an integer 
#### Define
- get the mean of the difference and add it to the min value
#### Code & Test

In [19]:
dfc.stop_duration.value_counts()

0-15 Min     47202
16-30 Min    11377
30+ Min       2642
2                1
Name: stop_duration, dtype: int64

In [20]:
dfc.stop_duration = dfc.stop_duration.replace(['0-15 Min','16-30 Min', '30+ Min'],[7.5, 23, 45]).astype(float)

In [21]:
dfc.stop_duration.value_counts()

7.5     47202
23.0    11377
45.0     2642
2.0         1
Name: stop_duration, dtype: int64

In [22]:
dfc.stop_duration.dtype

dtype('float64')

# Answering Questions
- For Speeding , were Men or Women stopped more often ? 
- Does gender affect who gets searched during a stop ?
- What is the mean stop_duration ?
- Compare the age distributions for each violation.

In [23]:
#1
dfc[dfc['violation']== 'Speeding']['driver_gender'].value_counts()

M    25458
F    11661
Name: driver_gender, dtype: int64

In [24]:
#2
dfc[dfc['search_conducted']== True]['driver_gender'].value_counts()

M    2111
F     366
Name: driver_gender, dtype: int64

In [25]:
#3
dfc.stop_duration.mean()

11.9985952762079

In [26]:
#4
dfc.groupby('violation')['driver_age'].describe()

,count,mean,std,min,25%,50%,75%,max
violation,,,,,,,,
Equipment,6507.0,31.682957,11.380671,16.0,23.0,28.0,39.0,81.0
Moving violation,11876.0,36.736443,13.258350,15.0,25.0,35.0,47.0,86.0
Other,3477.0,40.362381,12.754423,16.0,30.0,41.0,50.0,86.0
Registration/plates,2240.0,32.656696,11.150780,16.0,24.0,30.0,40.0,74.0
Seat belt,3.0,30.333333,10.214369,23.0,24.5,26.0,34.0,42.0
Speeding,37119.0,33.262803,12.615878,15.0,23.0,30.0,42.0,88.0

In [27]:
df.to_csv('police_cleaned.csv', index = False)